# Use an official Python runtime as a parent image
FROM cassandra

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY cassandra.yaml /etc/cassandra/cassandra.yaml
