apiVersion: v1
kind: Pod
metadata:
  name: aggregator
spec:
  restartPolicy: OnFailure
  containers:
    - name: aggregator
      image: aggregator:latest 
      imagePullPolicy: IfNotPresent
      env:
        - name: DATABASE_HOST
          value: "cassandra"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"

