apiVersion: v1
kind: Pod
metadata:
  name: aggregator
spec:
  containers:
    - name: aggregator
      image: aggregator:latest 
      imagePullPolicy: IfNotPresent
      env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "yourpassword"
