apiVersion: v1
kind: Pod
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  restartPolicy: OnFailure
  containers:
    - name: aggregator
      image: aggregator:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9090
      env:
        - name: DATABASE_HOST
          value: "cassandra"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30007
  selector:
    app: aggregator
