apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  template:
    spec:
      containers:
        - name: db-init
          image: db-init:latest 
          imagePullPolicy: IfNotPresent # Or use Never for strictly local development
          env:
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "yourpassword"
      restartPolicy: Never
