apiVersion: batch/v1
kind: Job
metadata:
  name: ingestion-worker-job
spec:
  parallelism: 5 # Replace with the desired number of parallel pods
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ingestion-worker
          image: ingestion-worker:latest
          imagePullPolicy: IfNotPresent 
          env:
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "yourpassword"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
